server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://118.24.36.128:3306/zfyc?rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:dao/*.xml
  configuration:
      cache-enabled: false
      local-cache-scope: statement