server:
  port: 52990
spring:
  datasource:
    url: jdbc:mysql://118.24.36.128:3306/zfyc?rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
      cache-enabled: false
      local-cache-scope: statement
  type-aliases-package: cn.com.zfyx.bean    # 设置mybatis pojo实体类的别名

fileUpload:
   path: /home/uploadFiles/img/static
   mappingPath: http://118.24.36.128:80/static
